{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.16.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "vyauz4nenfae3pnflghfygst5y"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-metadata-0.16.3-all.jar",
          "url": "atomicfu-0.16.3-all.jar",
          "size": 16000,
          "sha512": "574082e2d7086dd12ec9c582b4df1e9934b87925d7e7d027e8ea3adf8bd560c083b0a9113c3990236533338586f8f63dc583580a7ac58e8c9d599cf0552273c0",
          "sha256": "c3c0546dd33e0ef75782734d9703eb3583a28414b1d4464fcbde56d70a7d5a6d",
          "sha1": "b3d730ea4d198024b4f540a1716c1e57be939f12",
          "md5": "8dc4d8a669563135433e793d721778fd"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "atomicfu-0.16.3.jar",
          "url": "atomicfu-0.16.3.jar",
          "size": 9299,
          "sha512": "ee2e1425905a7988a4f56a8ce252ae6edb9f313dbe6b7c4fb9a98d1b465703b171e4f792d79a95aafbbd0c195da444453094be19b336784b93fe3a8e8e499860",
          "sha256": "5cd9fcb9f6b2be698b9e31cc05633486c8183c19f0c11cf4949d445fd587da19",
          "sha1": "3cde34906d393aa43c5536ea4d7516e73103a4c4",
          "md5": "d879b9d9a6598f74852fda87bfb7b93e"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm32/0.16.3/atomicfu-iosarm32-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm32",
        "version": "0.16.3"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm32/0.16.3/atomicfu-iosarm32-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm32",
        "version": "0.16.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.16.3/atomicfu-iosarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.16.3/atomicfu-iosarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.16.3/atomicfu-iossimulatorarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.16.3/atomicfu-iossimulatorarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.16.3/atomicfu-iosx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.16.3/atomicfu-iosx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.16.3/atomicfu-js-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.16.3"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.16.3/atomicfu-js-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.16.3"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.16.3/atomicfu-js-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.16.3"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.16.3/atomicfu-js-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.16.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.16.3/atomicfu-jvm-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.16.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.16.3/atomicfu-jvm-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.16.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxx64/0.16.3/atomicfu-linuxx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.16.3/atomicfu-macosarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.16.3/atomicfu-macosarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.16.3/atomicfu-macosx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.16.3/atomicfu-macosx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-mingwx64/0.16.3/atomicfu-mingwx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-mingwx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "mingwX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-mingwx64/0.16.3/atomicfu-mingwx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-mingwx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.16.3/atomicfu-tvosarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.16.3/atomicfu-tvosarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.16.3/atomicfu-tvossimulatorarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.16.3/atomicfu-tvossimulatorarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.16.3/atomicfu-tvosx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.16.3/atomicfu-tvosx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.16.3/atomicfu-watchosarm32-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.16.3/atomicfu-watchosarm32-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.16.3/atomicfu-watchosarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.16.3/atomicfu-watchosarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.16.3/atomicfu-watchossimulatorarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.16.3/atomicfu-watchossimulatorarm64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.16.3/atomicfu-watchosx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.16.3/atomicfu-watchosx64-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx86/0.16.3/atomicfu-watchosx86-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx86",
        "version": "0.16.3"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx86/0.16.3/atomicfu-watchosx86-0.16.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx86",
        "version": "0.16.3"
      }
    }
  ]
}
